
services:
  pipeline:
    build: .
    container_name: pump_pipeline
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - MQTT_BROKER_HOST=${MQTT_BROKER_HOST:-mosquitto}  
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    networks:
      - pump_network
    depends_on:
      - mosquitto
      - influxdb

  
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: pump_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
    networks:
      - pump_network
  
  influxdb:
    image: influxdb:2.8
    container_name: pump_influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - influx_data:/var/lib/influxdb2
    networks:
      - pump_network
    

networks:
  pump_network:
    driver: bridge

volumes:
  influx_data:
